name: C++ CI Build

on: [push, pull_request]

jobs:
  build-interpreter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug - list files
        run: ls -la
      - name: Build with Make
        run: make
        working-directory: interpreter
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with Make
        run: make
        working-directory: interpreter
      - name: Run Test
        run: ./compiler
        working-directory: interpreter
        
  # build-bytecode:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -name: checkout code
  #     uses: actions/checkout@v4
  #     -name: build
  #     run: make
  #     working-directory: bytecode
  #     -name: run
  #     run: ./compiler
  #     working-directory: bytecode